sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
env:
- PACKAGES="django>=1.10,<1.11 django-polymorphic<2.0"
- PACKAGES="django>=1.11,<1.12"
- PACKAGES="django>=2.0,<2.1"
- PACKAGES="django>=2.1,<2.2"
- PACKAGES="django>=3.0,<3.1"
matrix:
  exclude:
  - python: '2.7'
    env: PACKAGES="django>=2.0,<2.1"
  - python: '2.7'
    env: PACKAGES="django>=2.1,<2.2"
  - python: '2.7'
    env: PACKAGES="django>=2.2,<2.3"
  - python: '2.7'
    env: PACKAGES="django>=3.0,<3.1"
  - python: '3.5'
    env: PACKAGES="django>=3.0,<3.1"
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- pip install $PACKAGES -e .
script:
- coverage run --source=polymorphic_tree runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: WWNa4MHf50AOybB+XW9UKXCk/9Q8r++Jc4xTdEib43rj4odH9wxIaTRrzAbbpo3EO2gYuLgq6mMbaIZPD5l2UmgSnyuIbeYAAKIQblT+8XMamtXwnSS5j9vfBXYdj54rTlh+jKwEMW/JiQKl+SQpfQ2v1NMvYO63m89Ev9vXvcU=
    on_success: never
    on_failure: always
